- hosts: localhost
  tasks:
  - include_tasks: tasks/git-setup.yml
  - include_tasks: tasks/zsh.yml
  - include_tasks: tasks/node-setup.yml
  - include_tasks: tasks/npm-packages.yml
  - include_tasks: tasks/terminal-utils.yml
      
