  - name: Install node 
    apt:
      name: ['nodejs', 'npm']
    become: true
  - name: Install n
    npm: 
      name: n
      global: true
    become: true
  - name: Use node version 14
    shell: n 14
    become: true
