  - name: Install zsh  
    become: yes
    apt: name=zsh
    tags: ['install']
    
  - name: Change shell
    shell: chsh -s `which zsh`
    become: yes
    
  - name: Install Oh my zsh
    shell: curl -L https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    become_user: colinfaivre
